name: primo-accueil
namespace: mwolff44
version: 0.0.1
author: Mathias WOLFF
display_name: PRIMO ACCUEIL
min_wazo_version: 25.01
tags:
  - experimental
homepage: https://github.com/mwolff44/primo-accueil